name: 'Magento 2 Coding Style'
author: 'magic42'
description: 'Performs php static code analysis with the Magento 2 Coding Standard'
inputs:
  phpcs_standard:
    description: 'Path to your own PHPCS file or a specific standard. Leave empty to use "Magento2".'
    required: false
  phpcs_report:
    description: 'Report to output. Default: "checkstyle"'
    required: false
  phpcs_severity:
    description: 'Which severity to check for. Default: "8"'
    required: false
  phpcs_path:
    description: 'Path to the Magento 2 codebase. Default: "app/code/Magic42"'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'green'
